# Generated by Django 4.0.2 on 2022-02-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='dni',
            field=models.CharField(max_length=8),
        ),
    ]
